name: app_social
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.0.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   
  - assets/login.jpeg
  - assets/logIn.png
  # Tab
  - assets/tab_1.png
  - assets/tab_1s.png
  - assets/tab_2.png
  - assets/tab_2s.png
  - assets/tab_3.png
  - assets/tab_3s.png
  - assets/tab_4.png
  - assets/tab_4s.png

